title: Pinky Malinky's Stupid Blog
email: your-email@domain.com
description: You can update description in update blog details page.

baseurl: "/"
url: http://keralahost.in/pinkymalinky
google_adsense: Your-adsense-code

markdown: kramdown

name: Pinky Malinky's Stupid Blog

date: 2019-04-11 14:57:41 +0000
permalink: /:year/:month/:day/:title

logo: false
sass:
    load_paths:
        - _sass
        - bs
paginate: 10
adsid: ca-pub-8582082279264878
domain_name: http://keralahost.in/pinkymalinky/
google_analytics: UA-31XXXXXX-X
gems:
  - jekyll-paginate
  - jekyll-sitemap
cover: https://postimg.cc/bZkThKsy
author_image: https://postimg.cc/tZMPP5Yv

author: pinkymalinky
